### ISSUE TITLE
Negative memory usage?

### ISSUE THREAD

**Issue by aphelionz** [orbitdb/benchmark-runner#16]
Running the benchmarks in ipfs-log gives me 
![image](https://user-images.githubusercontent.com/106148/91662858-0e688d80-eab3-11ea-812e-f8fe930f21e2.png)

**Comment by tabcat** [comment]
looks like [global.gc()](https://github.com/orbitdb/benchmark-runner/blob/892d05b1246da10f480d75c63ecca1e420d4b913/cli.js#L101) is never called due to how [expose-gc](https://www.npmjs.com/package/expose-gc) is [imported](https://github.com/orbitdb/benchmark-runner/blob/892d05b1246da10f480d75c63ecca1e420d4b913/cli.js#L3).

It looks like according to expose-gc usage we should either use the global import and use `global.gc()` or import it as a function assigned to a local variable. What it looks like is happening right now is we are mixing them up, importing as a function and looking for the global variable.
